name: PR-CI-CD

on:
  pull_request_target:

jobs:
  close-external-prs:
    uses: crickets-and-comb/shared/.github/workflows/block_outside_PRs.yml@main
    with:
      ALLOWED_ORG: 'crickets-and-comb'
    secrets:
      ORG_READ_TOKEN: ${{ secrets.ORG_READ_TOKEN }}

  ci-cd:
    needs: close-external-prs
    # TODO: SWITCH BACK TO MAIN, here and in .gitmodules.
    uses: crickets-and-comb/reference_package/.github/workflows/CI_CD.yml@bugfix/KalebCoberly/checkout_PR_ref
    with:
      TEST_OR_PROD: 'dev'
    secrets:
      CHECKOUT_SHARED: ${{ secrets.CHECKOUT_SHARED }}
      SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}